[package]
name = "hello-world-guard-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies.risc0-zkvm]
version = "1.0.0-rc.2"
git = "ssh://git@github.com/risc0/risc0.git"
rev = "2cc59861385c0e9f1265cc3dac962beeb41c70ec"
default-features = false
