[package]
name = "hello-world-guard-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies.risc0-zkvm]
version = "1.0.0-rc.2"
git = "ssh://git@github.com/risc0/risc0.git"
rev = "78da97eb76ac61afa84a7bec5f55fa563aa8926d"
default-features = false
