[workspace]
members = [
  "hello_world",
]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
serde = { version = "1.0", default-features = false, features = ["derive"] }
snafu = { version = "0.7", default-features = false }

[workspace.dependencies.risc0-build]
git = "ssh://git@github.com/risc0/risc0.git"
rev = "1bb6db18e012261baf20c2011f38a1fd3fe72695"

[workspace.dependencies.risc0-zkvm]
git = "ssh://git@github.com/risc0/risc0.git"
rev = "1bb6db18e012261baf20c2011f38a1fd3fe72695"
default-features = false

[profile.dev]
opt-level = 3
