[workspace]
members = [
  "hello_world",
]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
serde = { version = "1.0", default-features = false, features = ["derive"] }
snafu = { version = "0.7", default-features = false }

[workspace.dependencies.risc0-build]
git = "ssh://git@github.com/risc0/risczero-wip.git"
rev = "a48c1750c6cdede81ee8eae77afe1ff646cb83b0"

[workspace.dependencies.risc0-zkvm]
git = "ssh://git@github.com/risc0/risczero-wip.git"
rev = "a48c1750c6cdede81ee8eae77afe1ff646cb83b0"
default-features = false

[profile.dev]
opt-level = 3
