[package]
name = "hw-guard-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies.risc0-zkvm]
version = "1.0.0-rc.2"
git = "ssh://git@github.com/risc0/risc0.git"
rev = "591072699f156f8ec7ddd0f41e9724c16b1a83d3"
default-features = false
